- name: Copy public key
  authorized_key:
    user: ec2-user
    state: present
    key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"

- name: Copy private key
  copy:
    src: /home/ubuntu/.ssh/id_rsa
    dest: /home/ec2-user/.ssh/id_rsa
    owner: ec2-user
    group: ec2-user
    mode: '0600'

- name: Copy private key
  copy:
    src: /home/ubuntu/.ssh/id_rsa.pub
    dest: /home/ec2-user/.ssh/id_rsa.pub
    owner: ec2-user
    group: ec2-user
    mode: '0600'
