- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: event_restart_prometheus

- name: systemd_reload 
  systemd:
    daemon_reload: yes

- name: Restart grafana service 
  service:
    name: grafana-server
    state: restarted 
