
#play to install grafana-server
- name: Add grafana official repo
  template:
    src: "grafana.repo.j2"
    dest: "{{ grafana_repo_path }}"

- name: Install latest grafana version 
  yum:
    name: grafana
    state: present

- name: Add data source in Grafana 
  template:
    src: "datasources.yaml"
    dest: '/etc/grafana/provisioning/datasources/datasources.yaml'
    owner: root
    group: grafana
    mode: 0770
  #notify: Restart grafana

- name: Adding dashboard provisioning file
  copy:
    src: "dashboards.yaml"
    dest: '/etc/grafana/provisioning/dashboards/dashboards.yaml'
    owner: root
    group: grafana
    mode: 0640
  #notify: Restart grafana

- name: Create a directory for adding dashboards
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana
    mode: 0755

- name: Add available  json dashboards
  copy:
    src: "sample_dashboard.json"
    dest: '/var/lib/grafana/dashboards/sample_dashboard.json'
    owner: grafana
    group: grafana
    mode: 0644
  notify: Restart grafana service

- name: start and enable grafana-serevr
  service:
    name: grafana-server
    state: started
    enabled: yes
