# playbook to install prometheus node exporter
- name: Create directory for node exporter agent
  file:
    path: "{{ exporter_dir }}"
    state: directory
    owner: root
    mode: 0755

- name: Download and untar prometheus Node Exporter binary file
  unarchive:
    src: "{{ node_exporter_download_link }}"
    dest: "{{ exporter_dir }}"
    remote_src: yes

- name: Copy node exporter binary file to /usr/local/bin directory
  copy:
    src: "{{ agent_path }}"
    dest: "/usr/local/bin/"
    mode: 0755
    remote_src: yes

- name: Create systemd init service file for Prometheus Node exporter
  template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
    owner: root
    mode: 0644

- name: Start and enable node_exporter service
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: check if node_exporter collects metrics from localhost
  uri:
    url: "{{ metrics_uri }}"
    method: GET
    status_code: '200'
  ignore_errors: true
