# node_exporter variables
exporter_dir: "/exporter"

agent_path: "{{ exporter_dir }}/node_exporter-{{ version }}.linux-amd64/node_exporter"

service_name: "node_exporter"

version: 1.7.0

exec_command: "/usr/local/bin/node_exporter"

node_exporter_download_link: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz"

metrics_uri: "http://localhost:9100/metrics"

# cloudwatch agent variables

download_link_agent: "https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm"

start_cloudwatch_agent: "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s"
