# Add hosts info to host file
#- name: Add hosts info to /etc/hosts
#  lineinfile:
##    dest: /etc/hosts
 #   line: "{{ hostvars[item].ansible_default_ipv4.address }}\t{{ hostvars[item].ansible_hostname }}\t{{ hostvars[item].ansible_nodename }}"
#  with_items:
#    - "{{ ansible_play_hosts|default([]) }}"

# Raise mongod ulimit
# https://docs.mongodb.com/manual/reference/ulimit/
- name: Copy ulimit config file to /etc/security/limits.d/
  copy: 
    src: nproc_limits.conf
    dest: /etc/security/limits.d/99-mongodb-nproc.conf

# Configure sufficient file handles, kernel pid limit, and max threads/process
- name: Configure sufficient file handles (98000)
  shell: echo 1587099 | tee /proc/sys/fs/file-max #1587099

- name: Configure sufficient kernel pid limit (64000)
  shell: echo 64000 | tee /proc/sys/kernel/pid_max #32768

- name: Configure sufficient max threads per process (64000)
  shell: echo 124330 | tee /proc/sys/kernel/threads-max #124330

- name: Persist fs.file-max, kernel.pid_max, kernel.threads-max on reboot
  shell: >
    echo "fs.file-max = 1587099" | tee -a /etc/sysctl.conf &&
    echo "kernel.pid_max = 64000" | tee -a /etc/sysctl.conf &&
    echo "kernel.threads-max = 124330" | tee -a /etc/sysctl.conf