name: Deploy to RabbitMQ

on:
  push:
    branches:
      - main  # Change this to your branch if needed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      #- name: Set up Python
       # uses: actions/setup-python@v4
        #with:
         # python-version: '3.x'

      - name: Install pip if missing
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip

      - name: Install Ansible
        run: |
          python3 -m pip install ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i hosts main.yaml -vvvv
