name: Deploy to RabbitMQ

on:
  push:
    branches:
      - main  # Change this to your branch if needed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v1  # Updated to the latest version

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'  # Disable host key checking
        run: |
          ansible-playbook -i hosts main.yaml -vvvv  # Run the playbook with verbose output